name: Development

on:
  push:
    branches: [ develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_DATABASE: testing_db
          MYSQL_ROOT_PASSWORD: password
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testing_db
      DB_USERNAME: root
      DB_PASSWORD: password
    steps:
      - name: PHP実行環境を展開する
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: 8
      - name: チェックアウトアクションを実行する
        uses: actions/checkout@v2
      - name: Laravelをセットアップする
        uses: ./.github/steps/setup-laravel
      - name: テストを実行する
        run: vendor/bin/phpunit
  deployment:
    runs-on: ubuntu-latest
    env:
      AWS_CODE_DEPLOY_APPLICATION_NAME: development-app-name
      AWS_CODE_DEPLOY_GROUP_NAME: development-group-name
    steps:
      - name: aws-cliをインストールする
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: CodeDeployを実行する
        run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION_NAME }} --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP_NAME }} --github-location repository="${{ github.repository }}",commitId="${{ github.sha }}"
