name: Laravel
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DB_VERSION: 8
  DB_DATABASE: testdb
  PHP_VERSION: 8
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:${env.DB_VERSION}
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${env.DB_DATABASE}
          MYSQL_ROOT_PASSWORD: password
    steps:
    - name: PHP実行環境を展開する
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: ${env.PHP_VERSION}
    - name: チェックアウトアクションを実行する
      uses: actions/checkout@v2
    - name: .envをコピーする
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: PHPライブラリをインストールする
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: LaravelのApp keyを作成する
      run: php artisan key:generate
    - name: ディレクトリの権限を変更する
      run: chmod -R 777 storage bootstrap/cache
    - name: DBをマイグレートする
      run: php artisan migrate
    - name: テストを実行する
      run: vendor/bin/phpunit
